<a href="https://colab.research.google.com/github/Regina1832/Acronyms/blob/A-course-in-ML/KMeans_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.cluster import KMeans

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
X = np.array([[1, 2], [1, 4], [5, 2], [5, 4], [9, 2], [9, 4]])

In [4]:
model = KMeans(n_clusters=3, random_state=0)

In [5]:
y = model.fit(X)

In [6]:
y.labels_

array([1, 1, 2, 2, 0, 0], dtype=int32)

In [7]:
y.predict([[0, 0]])

array([1], dtype=int32)

In [8]:
y.cluster_centers_

array([[9., 3.],
       [1., 3.],
       [5., 3.]])

In [9]:
y.cluster_centers_[0]

array([9., 3.])